// ============================================================
// src/models/customer.model.js
// Defines the structure of a customer/client profile.
// This is the person who has hired TDC to find them a match.
// ============================================================

// These are TDC's actual paying clients (10 male + 5 female)
// Fields are based on Indian matrimonial app standards
const customers = [
  {
    id: "c001",
    firstName: "Rohan",
    lastName: "Kapoor",
    gender: "Male",
    dateOfBirth: "1994-03-15",
    age: 30,
    country: "India",
    city: "Mumbai",
    height: 178, // in cm
    email: "rohan.kapoor@gmail.com",
    phone: "+91-9876543201",
    undergraduateCollege: "IIT Bombay",
    degree: "B.Tech Computer Science",
    income: 2200000, // annual in INR
    currentCompany: "Google India",
    designation: "Software Engineer",
    maritalStatus: "Never Married",
    languagesKnown: ["Hindi", "English", "Marathi"],
    siblings: 1,
    caste: "Kayastha",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "Maybe",
    // Indian matrimonial specific fields
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "Occasionally",
    motherTongue: "Hindi",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Fair",
    gotra: "Kashyap",
    horoscopeMatch: "Preferred",
    fathersOccupation: "Business",
    mothersOccupation: "Homemaker",
    ownHouse: "Yes",
    status: "Active",
    notes: "Looking for a well-educated partner. Family-oriented.",
    profilePhoto: null,
  },
  {
    id: "c002",
    firstName: "Aarav",
    lastName: "Mehta",
    gender: "Male",
    dateOfBirth: "1992-07-22",
    age: 32,
    country: "India",
    city: "Delhi",
    height: 182,
    email: "aarav.mehta@gmail.com",
    phone: "+91-9876543202",
    undergraduateCollege: "Delhi University",
    degree: "MBA Finance",
    income: 3500000,
    currentCompany: "HDFC Bank",
    designation: "Vice President",
    maritalStatus: "Never Married",
    languagesKnown: ["Hindi", "English", "Punjabi"],
    siblings: 2,
    caste: "Agarwal",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "No",
    diet: "Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Hindi",
    familyType: "Joint",
    manglik: "No",
    complexion: "Wheatish",
    gotra: "Garg",
    horoscopeMatch: "Must",
    fathersOccupation: "Business",
    mothersOccupation: "Homemaker",
    ownHouse: "Yes",
    status: "Active",
    notes: "Traditional family values. Looking for vegetarian partner.",
    profilePhoto: null,
  },
  {
    id: "c003",
    firstName: "Vikram",
    lastName: "Singh",
    gender: "Male",
    dateOfBirth: "1995-11-08",
    age: 29,
    country: "India",
    city: "Bangalore",
    height: 175,
    email: "vikram.singh@gmail.com",
    phone: "+91-9876543203",
    undergraduateCollege: "BITS Pilani",
    degree: "B.Tech Electronics",
    income: 1800000,
    currentCompany: "Infosys",
    designation: "Senior Developer",
    maritalStatus: "Never Married",
    languagesKnown: ["Hindi", "English", "Kannada"],
    siblings: 0,
    caste: "Rajput",
    religion: "Hindu",
    wantKids: "Maybe",
    openToRelocate: "Yes",
    openToPets: "Yes",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "Occasionally",
    motherTongue: "Hindi",
    familyType: "Nuclear",
    manglik: "Yes",
    complexion: "Wheatish",
    gotra: "Bharadwaj",
    horoscopeMatch: "Not Important",
    fathersOccupation: "Government Service",
    mothersOccupation: "Teacher",
    ownHouse: "No",
    status: "Active",
    notes: "Open-minded. Looking for someone career-driven.",
    profilePhoto: null,
  },
  {
    id: "c004",
    firstName: "Aryan",
    lastName: "Patel",
    gender: "Male",
    dateOfBirth: "1993-05-19",
    age: 31,
    country: "India",
    city: "Ahmedabad",
    height: 170,
    email: "aryan.patel@gmail.com",
    phone: "+91-9876543204",
    undergraduateCollege: "Gujarat University",
    degree: "B.Com",
    income: 1500000,
    currentCompany: "Family Business",
    designation: "Director",
    maritalStatus: "Never Married",
    languagesKnown: ["Gujarati", "Hindi", "English"],
    siblings: 3,
    caste: "Patel",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "No",
    openToPets: "No",
    diet: "Jain",
    smoking: "No",
    drinking: "No",
    motherTongue: "Gujarati",
    familyType: "Joint",
    manglik: "No",
    complexion: "Fair",
    gotra: "Vasishtha",
    horoscopeMatch: "Preferred",
    fathersOccupation: "Business",
    mothersOccupation: "Homemaker",
    ownHouse: "Yes",
    status: "On Hold",
    notes: "Looking for a Jain girl from Gujarat ideally.",
    profilePhoto: null,
  },
  {
    id: "c005",
    firstName: "Kabir",
    lastName: "Khan",
    gender: "Male",
    dateOfBirth: "1991-09-30",
    age: 33,
    country: "India",
    city: "Hyderabad",
    height: 180,
    email: "kabir.khan@gmail.com",
    phone: "+91-9876543205",
    undergraduateCollege: "Osmania University",
    degree: "B.Tech Civil",
    income: 2800000,
    currentCompany: "L&T Construction",
    designation: "Project Manager",
    maritalStatus: "Never Married",
    languagesKnown: ["Urdu", "Hindi", "English", "Telugu"],
    siblings: 1,
    caste: "Sheikh",
    religion: "Muslim",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "No",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Urdu",
    familyType: "Joint",
    manglik: "N/A",
    complexion: "Wheatish",
    gotra: "N/A",
    horoscopeMatch: "Not Important",
    fathersOccupation: "Business",
    mothersOccupation: "Homemaker",
    ownHouse: "Yes",
    status: "Active",
    notes: "Looking for educated Muslim girl. Open to relocation.",
    profilePhoto: null,
  },
  {
    id: "c006",
    firstName: "Rahul",
    lastName: "Joshi",
    gender: "Male",
    dateOfBirth: "1996-01-14",
    age: 28,
    country: "India",
    city: "Pune",
    height: 173,
    email: "rahul.joshi@gmail.com",
    phone: "+91-9876543206",
    undergraduateCollege: "Pune University",
    degree: "B.Tech IT",
    income: 1200000,
    currentCompany: "TCS",
    designation: "System Analyst",
    maritalStatus: "Never Married",
    languagesKnown: ["Marathi", "Hindi", "English"],
    siblings: 1,
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "Yes",
    diet: "Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Marathi",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Fair",
    gotra: "Atri",
    horoscopeMatch: "Preferred",
    fathersOccupation: "Teacher",
    mothersOccupation: "Teacher",
    ownHouse: "No",
    status: "Active",
    notes: "Loves travel and books. Looking for like-minded partner.",
    profilePhoto: null,
  },
  {
    id: "c007",
    firstName: "Dev",
    lastName: "Malhotra",
    gender: "Male",
    dateOfBirth: "1990-06-25",
    age: 34,
    country: "UAE",
    city: "Dubai",
    height: 183,
    email: "dev.malhotra@gmail.com",
    phone: "+971-501234567",
    undergraduateCollege: "Symbiosis Pune",
    degree: "MBA Marketing",
    income: 6000000,
    currentCompany: "Emirates Group",
    designation: "Regional Manager",
    maritalStatus: "Divorced",
    languagesKnown: ["Hindi", "English", "Punjabi"],
    siblings: 2,
    caste: "Khatri",
    religion: "Hindu",
    wantKids: "Maybe",
    openToRelocate: "No",
    openToPets: "Yes",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "Occasionally",
    motherTongue: "Punjabi",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Fair",
    gotra: "Kashyap",
    horoscopeMatch: "Not Important",
    fathersOccupation: "Business",
    mothersOccupation: "Doctor",
    ownHouse: "Yes",
    status: "Active",
    notes: "Based in Dubai. Looking for a partner willing to relocate abroad.",
    profilePhoto: null,
  },
  {
    id: "c008",
    firstName: "Nikhil",
    lastName: "Reddy",
    gender: "Male",
    dateOfBirth: "1994-12-03",
    age: 30,
    country: "India",
    city: "Chennai",
    height: 172,
    email: "nikhil.reddy@gmail.com",
    phone: "+91-9876543208",
    undergraduateCollege: "IIT Madras",
    degree: "M.Tech AI",
    income: 2500000,
    currentCompany: "Zoho Corp",
    designation: "AI Engineer",
    maritalStatus: "Never Married",
    languagesKnown: ["Telugu", "Tamil", "Hindi", "English"],
    siblings: 1,
    caste: "Reddy",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "Maybe",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Telugu",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Wheatish",
    gotra: "Vasishtha",
    horoscopeMatch: "Not Important",
    fathersOccupation: "Engineer",
    mothersOccupation: "Doctor",
    ownHouse: "No",
    status: "Matched",
    notes: "Highly educated. Prefers someone in tech or medicine.",
    profilePhoto: null,
  },
  {
    id: "c009",
    firstName: "Aditya",
    lastName: "Verma",
    gender: "Male",
    dateOfBirth: "1993-08-11",
    age: 31,
    country: "India",
    city: "Lucknow",
    height: 176,
    email: "aditya.verma@gmail.com",
    phone: "+91-9876543209",
    undergraduateCollege: "Lucknow University",
    degree: "MBBS",
    income: 1800000,
    currentCompany: "Medanta Hospital",
    designation: "Resident Doctor",
    maritalStatus: "Never Married",
    languagesKnown: ["Hindi", "English"],
    siblings: 2,
    caste: "Kayastha",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "No",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Hindi",
    familyType: "Joint",
    manglik: "No",
    complexion: "Fair",
    gotra: "Parashar",
    horoscopeMatch: "Preferred",
    fathersOccupation: "Doctor",
    mothersOccupation: "Homemaker",
    ownHouse: "Yes",
    status: "Active",
    notes: "Doctor looking for educated partner. Prefers medical or business background.",
    profilePhoto: null,
  },
  {
    id: "c010",
    firstName: "Siddharth",
    lastName: "Nair",
    gender: "Male",
    dateOfBirth: "1997-04-07",
    age: 27,
    country: "India",
    city: "Kochi",
    height: 174,
    email: "siddharth.nair@gmail.com",
    phone: "+91-9876543210",
    undergraduateCollege: "Cochin University",
    degree: "B.Tech Mechanical",
    income: 900000,
    currentCompany: "KPMG",
    designation: "Business Analyst",
    maritalStatus: "Never Married",
    languagesKnown: ["Malayalam", "English", "Hindi"],
    siblings: 1,
    caste: "Nair",
    religion: "Hindu",
    wantKids: "Maybe",
    openToRelocate: "Yes",
    openToPets: "Yes",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "Occasionally",
    motherTongue: "Malayalam",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Wheatish",
    gotra: "N/A",
    horoscopeMatch: "Not Important",
    fathersOccupation: "Business",
    mothersOccupation: "Teacher",
    ownHouse: "No",
    status: "Active",
    notes: "Young professional. Open to all cultures.",
    profilePhoto: null,
  },
  // ── Female clients ──
  {
    id: "c011",
    firstName: "Ananya",
    lastName: "Sharma",
    gender: "Female",
    dateOfBirth: "1995-02-28",
    age: 29,
    country: "India",
    city: "Delhi",
    height: 163,
    email: "ananya.sharma@gmail.com",
    phone: "+91-9876543211",
    undergraduateCollege: "Lady Shri Ram College",
    degree: "BA Economics",
    income: 1200000,
    currentCompany: "McKinsey",
    designation: "Business Analyst",
    maritalStatus: "Never Married",
    languagesKnown: ["Hindi", "English", "French"],
    siblings: 1,
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Maybe",
    openToRelocate: "Yes",
    openToPets: "Yes",
    diet: "Vegetarian",
    smoking: "No",
    drinking: "Occasionally",
    motherTongue: "Hindi",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Fair",
    gotra: "Atri",
    horoscopeMatch: "Not Important",
    fathersOccupation: "IAS Officer",
    mothersOccupation: "Professor",
    ownHouse: "Yes",
    status: "Active",
    notes: "Career-driven. Looking for an ambitious, well-educated partner.",
    profilePhoto: null,
  },
  {
    id: "c012",
    firstName: "Meera",
    lastName: "Iyer",
    gender: "Female",
    dateOfBirth: "1993-10-15",
    age: 31,
    country: "India",
    city: "Bangalore",
    height: 158,
    email: "meera.iyer@gmail.com",
    phone: "+91-9876543212",
    undergraduateCollege: "IISc Bangalore",
    degree: "M.Tech Biotechnology",
    income: 1500000,
    currentCompany: "Biocon",
    designation: "Research Scientist",
    maritalStatus: "Never Married",
    languagesKnown: ["Tamil", "Kannada", "English", "Hindi"],
    siblings: 0,
    caste: "Iyer",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Yes",
    diet: "Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Tamil",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Wheatish",
    gotra: "Vasishtha",
    horoscopeMatch: "Preferred",
    fathersOccupation: "Professor",
    mothersOccupation: "Doctor",
    ownHouse: "No",
    status: "Active",
    notes: "Scientist. Values intellect and shared professional respect.",
    profilePhoto: null,
  },
  {
    id: "c013",
    firstName: "Zara",
    lastName: "Shaikh",
    gender: "Female",
    dateOfBirth: "1996-06-20",
    age: 28,
    country: "India",
    city: "Mumbai",
    height: 165,
    email: "zara.shaikh@gmail.com",
    phone: "+91-9876543213",
    undergraduateCollege: "Sophia College Mumbai",
    degree: "B.A Mass Communication",
    income: 800000,
    currentCompany: "NDTV",
    designation: "Journalist",
    maritalStatus: "Never Married",
    languagesKnown: ["Urdu", "Hindi", "English"],
    siblings: 2,
    caste: "Shaikh",
    religion: "Muslim",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "No",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Urdu",
    familyType: "Joint",
    manglik: "N/A",
    complexion: "Fair",
    gotra: "N/A",
    horoscopeMatch: "Not Important",
    fathersOccupation: "Business",
    mothersOccupation: "Homemaker",
    ownHouse: "Yes",
    status: "Active",
    notes: "Looking for a well-settled Muslim professional.",
    profilePhoto: null,
  },
  {
    id: "c014",
    firstName: "Divya",
    lastName: "Nambiar",
    gender: "Female",
    dateOfBirth: "1994-09-05",
    age: 30,
    country: "India",
    city: "Kochi",
    height: 160,
    email: "divya.nambiar@gmail.com",
    phone: "+91-9876543214",
    undergraduateCollege: "Kerala Medical College",
    degree: "MBBS, MD Gynecology",
    income: 2200000,
    currentCompany: "AIIMS Kochi",
    designation: "Senior Resident",
    maritalStatus: "Never Married",
    languagesKnown: ["Malayalam", "English", "Hindi"],
    siblings: 1,
    caste: "Nambiar",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Maybe",
    diet: "Non-Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Malayalam",
    familyType: "Nuclear",
    manglik: "No",
    complexion: "Wheatish",
    gotra: "N/A",
    horoscopeMatch: "Not Important",
    fathersOccupation: "Doctor",
    mothersOccupation: "Teacher",
    ownHouse: "Yes",
    status: "Active",
    notes: "Doctor. Looking for someone equally accomplished and supportive.",
    profilePhoto: null,
  },
  {
    id: "c015",
    firstName: "Pooja",
    lastName: "Agarwal",
    gender: "Female",
    dateOfBirth: "1995-12-10",
    age: 29,
    country: "India",
    city: "Jaipur",
    height: 162,
    email: "pooja.agarwal@gmail.com",
    phone: "+91-9876543215",
    undergraduateCollege: "NIFT Delhi",
    degree: "B.Design Fashion",
    income: 1000000,
    currentCompany: "Fabindia",
    designation: "Senior Designer",
    maritalStatus: "Never Married",
    languagesKnown: ["Hindi", "English", "Rajasthani"],
    siblings: 2,
    caste: "Agarwal",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "Yes",
    diet: "Vegetarian",
    smoking: "No",
    drinking: "No",
    motherTongue: "Hindi",
    familyType: "Joint",
    manglik: "No",
    complexion: "Fair",
    gotra: "Garg",
    horoscopeMatch: "Preferred",
    fathersOccupation: "Business",
    mothersOccupation: "Homemaker",
    ownHouse: "Yes",
    status: "Active",
    notes: "Creative professional. Looking for a cultured, family-oriented partner.",
    profilePhoto: null,
  },
];

// Helper to get all customers
export const getAllCustomers = () => customers;

// Helper to find a customer by ID
export const findCustomerById = (id) => customers.find((c) => c.id === id);

// Helper to get customers assigned to a specific matchmaker
export const getCustomersByIds = (ids) =>
  customers.filter((c) => ids.includes(c.id));
