// ============================================================
// src/models/matchPool.model.js
// This contains 100+ dummy profiles that are used as the
// matching pool. When a customer needs a match, the algorithm
// searches through these profiles to find the best candidates.
// ============================================================

// Generate a large pool of profiles (50 female + 50 male)
// These are potential matches shown to TDC clients

const femaleProfiles = [
  { id: "f001", firstName: "Priya", lastName: "Sharma", gender: "Female", age: 26, dateOfBirth: "1998-03-10", city: "Mumbai", country: "India", height: 160, income: 800000, degree: "B.Tech CS", currentCompany: "Wipro", designation: "Developer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f002", firstName: "Sneha", lastName: "Patel", gender: "Female", age: 24, dateOfBirth: "2000-07-15", city: "Ahmedabad", country: "India", height: 155, income: 600000, degree: "B.Com", currentCompany: "Self-employed", designation: "Business Owner", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Patel", diet: "Jain", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Joint", manglik: "No", languagesKnown: ["Gujarati", "Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f003", firstName: "Riya", lastName: "Kapoor", gender: "Female", age: 27, dateOfBirth: "1997-01-20", city: "Delhi", country: "India", height: 163, income: 1100000, degree: "MBA", currentCompany: "Deloitte", designation: "Consultant", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Khatri", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f004", firstName: "Isha", lastName: "Mehta", gender: "Female", age: 25, dateOfBirth: "1999-05-12", city: "Bangalore", country: "India", height: 158, income: 900000, degree: "B.Tech IT", currentCompany: "Amazon", designation: "SDE-1", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Maybe", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Kannada"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "f005", firstName: "Pooja", lastName: "Singh", gender: "Female", age: 28, dateOfBirth: "1996-09-03", city: "Chennai", country: "India", height: 161, income: 1000000, degree: "MBBS", currentCompany: "Apollo Hospital", designation: "Junior Doctor", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "Yes", languagesKnown: ["Hindi", "English", "Tamil"], siblings: 1, horoscopeMatch: "Preferred" },
  { id: "f006", firstName: "Anita", lastName: "Reddy", gender: "Female", age: 26, dateOfBirth: "1998-11-25", city: "Hyderabad", country: "India", height: 157, income: 850000, degree: "B.Tech ECE", currentCompany: "Tech Mahindra", designation: "Software Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Reddy", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Telugu", familyType: "Nuclear", manglik: "No", languagesKnown: ["Telugu", "Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "f007", firstName: "Kavya", lastName: "Nair", gender: "Female", age: 25, dateOfBirth: "1999-04-17", city: "Kochi", country: "India", height: 159, income: 700000, degree: "B.Arch", currentCompany: "DLF", designation: "Junior Architect", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Nair", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "No", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f008", firstName: "Nisha", lastName: "Joshi", gender: "Female", age: 27, dateOfBirth: "1997-08-30", city: "Pune", country: "India", height: 162, income: 950000, degree: "M.Com Finance", currentCompany: "ICICI Bank", designation: "Relationship Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Marathi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Preferred" },
  { id: "f009", firstName: "Simran", lastName: "Kaur", gender: "Female", age: 24, dateOfBirth: "2000-02-14", city: "Chandigarh", country: "India", height: 164, income: 750000, degree: "B.A Psychology", currentCompany: "Practo", designation: "Content Writer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Sikh", caste: "Jat", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Punjabi", "Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "f010", firstName: "Meghna", lastName: "Iyer", gender: "Female", age: 29, dateOfBirth: "1995-06-08", city: "Bangalore", country: "India", height: 156, income: 1300000, degree: "M.Tech AI", currentCompany: "Google", designation: "ML Engineer", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "No", openToPets: "Yes", religion: "Hindu", caste: "Iyer", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tamil", familyType: "Nuclear", manglik: "No", languagesKnown: ["Tamil", "Kannada", "English"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "f011", firstName: "Anika", lastName: "Verma", gender: "Female", age: 26, dateOfBirth: "1998-12-01", city: "Lucknow", country: "India", height: 160, income: 650000, degree: "B.Sc Nursing", currentCompany: "SGPGI Hospital", designation: "Staff Nurse", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Kayastha", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f012", firstName: "Tara", lastName: "Malhotra", gender: "Female", age: 28, dateOfBirth: "1996-03-22", city: "Mumbai", country: "India", height: 165, income: 1800000, degree: "LLB", currentCompany: "AZB Partners", designation: "Associate Lawyer", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "No", openToPets: "Yes", religion: "Hindu", caste: "Khatri", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f013", firstName: "Fatima", lastName: "Khan", gender: "Female", age: 25, dateOfBirth: "1999-10-18", city: "Hyderabad", country: "India", height: 158, income: 700000, degree: "B.Pharma", currentCompany: "Dr. Reddy's Lab", designation: "Research Associate", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Muslim", caste: "Sheikh", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Urdu", familyType: "Joint", manglik: "N/A", languagesKnown: ["Urdu", "Telugu", "Hindi", "English"], siblings: 3, horoscopeMatch: "Not Important" },
  { id: "f014", firstName: "Deepika", lastName: "Pillai", gender: "Female", age: 27, dateOfBirth: "1997-07-11", city: "Trivandrum", country: "India", height: 161, income: 900000, degree: "MCA", currentCompany: "UST Global", designation: "Software Developer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Maybe", religion: "Hindu", caste: "Nair", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "No", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f015", firstName: "Shruti", lastName: "Agarwal", gender: "Female", age: 26, dateOfBirth: "1998-05-29", city: "Jaipur", country: "India", height: 157, income: 600000, degree: "B.Des", currentCompany: "Myntra", designation: "UI Designer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Agarwal", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English", "Rajasthani"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f016", firstName: "Lavanya", lastName: "Krishnan", gender: "Female", age: 25, dateOfBirth: "1999-01-05", city: "Chennai", country: "India", height: 155, income: 750000, degree: "B.E Mechanical", currentCompany: "TVS Motors", designation: "Graduate Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tamil", familyType: "Nuclear", manglik: "No", languagesKnown: ["Tamil", "English", "Hindi"], siblings: 1, horoscopeMatch: "Preferred" },
  { id: "f017", firstName: "Komal", lastName: "Shah", gender: "Female", age: 24, dateOfBirth: "2000-09-20", city: "Surat", country: "India", height: 154, income: 500000, degree: "B.Com", currentCompany: "Family Business", designation: "Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Baniya", diet: "Jain", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Joint", manglik: "No", languagesKnown: ["Gujarati", "Hindi"], siblings: 3, horoscopeMatch: "Must" },
  { id: "f018", firstName: "Pallavi", lastName: "Dubey", gender: "Female", age: 27, dateOfBirth: "1997-04-14", city: "Bhopal", country: "India", height: 159, income: 800000, degree: "M.A Hindi Literature", currentCompany: "NCERT", designation: "Content Developer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English", "Sanskrit"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f019", firstName: "Ritika", lastName: "Bose", gender: "Female", age: 28, dateOfBirth: "1996-11-09", city: "Kolkata", country: "India", height: 162, income: 1000000, degree: "MBA HR", currentCompany: "ITC Limited", designation: "HR Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Bengali", familyType: "Nuclear", manglik: "No", languagesKnown: ["Bengali", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f020", firstName: "Swati", lastName: "Kulkarni", gender: "Female", age: 26, dateOfBirth: "1998-06-27", city: "Nashik", country: "India", height: 160, income: 700000, degree: "B.Tech Chemical", currentCompany: "Hindustan Unilever", designation: "Process Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Maybe", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Marathi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f021", firstName: "Bhavna", lastName: "Trivedi", gender: "Female", age: 25, dateOfBirth: "1999-02-18", city: "Vadodara", country: "India", height: 156, income: 580000, degree: "B.A Fine Arts", currentCompany: "Freelance", designation: "Artist", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Nuclear", manglik: "No", languagesKnown: ["Gujarati", "Hindi", "English"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "f022", firstName: "Minal", lastName: "Chavan", gender: "Female", age: 27, dateOfBirth: "1997-10-05", city: "Aurangabad", country: "India", height: 158, income: 750000, degree: "B.Pharm", currentCompany: "Sun Pharma", designation: "Quality Analyst", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Marathi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Preferred" },
  { id: "f023", firstName: "Salma", lastName: "Mirza", gender: "Female", age: 26, dateOfBirth: "1998-08-13", city: "Lucknow", country: "India", height: 161, income: 900000, degree: "B.A Economics", currentCompany: "RBI", designation: "Grade B Officer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Muslim", caste: "Mirza", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Urdu", familyType: "Joint", manglik: "N/A", languagesKnown: ["Urdu", "Hindi", "English"], siblings: 3, horoscopeMatch: "Not Important" },
  { id: "f024", firstName: "Aditi", lastName: "Mishra", gender: "Female", age: 25, dateOfBirth: "1999-04-22", city: "Varanasi", country: "India", height: 157, income: 650000, degree: "B.Ed", currentCompany: "Kendriya Vidyalaya", designation: "Teacher", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English", "Sanskrit"], siblings: 2, horoscopeMatch: "Must" },
  { id: "f025", firstName: "Chandni", lastName: "Rawat", gender: "Female", age: 26, dateOfBirth: "1998-01-11", city: "Dehradun", country: "India", height: 163, income: 720000, degree: "MBA Tourism", currentCompany: "MakeMyTrip", designation: "Travel Consultant", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f026", firstName: "Tanvi", lastName: "Goyal", gender: "Female", age: 27, dateOfBirth: "1997-03-16", city: "Chandigarh", country: "India", height: 162, income: 1100000, degree: "CA", currentCompany: "KPMG", designation: "Senior Associate", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Agarwal", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f027", firstName: "Jyoti", lastName: "Pandey", gender: "Female", age: 25, dateOfBirth: "1999-07-29", city: "Allahabad", country: "India", height: 159, income: 600000, degree: "M.Sc Chemistry", currentCompany: "DRDO", designation: "Junior Scientist", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f028", firstName: "Aishwarya", lastName: "Rajan", gender: "Female", age: 28, dateOfBirth: "1996-09-14", city: "Coimbatore", country: "India", height: 157, income: 1200000, degree: "M.Tech Computer Science", currentCompany: "Cognizant", designation: "Technical Lead", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tamil", familyType: "Nuclear", manglik: "No", languagesKnown: ["Tamil", "English", "Hindi"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "f029", firstName: "Preeti", lastName: "Rana", gender: "Female", age: 26, dateOfBirth: "1998-12-19", city: "Shimla", country: "India", height: 160, income: 680000, degree: "B.H.M Hotel Management", currentCompany: "Taj Hotels", designation: "F&B Executive", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f030", firstName: "Mansi", lastName: "Desai", gender: "Female", age: 25, dateOfBirth: "1999-05-06", city: "Rajkot", country: "India", height: 155, income: 540000, degree: "B.Sc Nutrition", currentCompany: "Nestle India", designation: "Nutritionist", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Patel", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Joint", manglik: "No", languagesKnown: ["Gujarati", "Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f031", firstName: "Neha", lastName: "Gupta", gender: "Female", age: 27, dateOfBirth: "1997-02-08", city: "Delhi", country: "India", height: 162, income: 950000, degree: "B.Tech CSE", currentCompany: "Flipkart", designation: "Product Manager", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Agarwal", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f032", firstName: "Shikha", lastName: "Rao", gender: "Female", age: 26, dateOfBirth: "1998-10-31", city: "Pune", country: "India", height: 161, income: 880000, degree: "MBA Operations", currentCompany: "Infosys BPO", designation: "Operations Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Maybe", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Kannada", familyType: "Nuclear", manglik: "No", languagesKnown: ["Kannada", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f033", firstName: "Yamini", lastName: "Shetty", gender: "Female", age: 25, dateOfBirth: "1999-08-23", city: "Mangalore", country: "India", height: 158, income: 720000, degree: "B.Com CA inter", currentCompany: "PwC", designation: "Audit Associate", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Shetty", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tulu", familyType: "Nuclear", manglik: "No", languagesKnown: ["Tulu", "Kannada", "Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "f034", firstName: "Harsha", lastName: "Naidu", gender: "Female", age: 27, dateOfBirth: "1997-06-12", city: "Visakhapatnam", country: "India", height: 160, income: 820000, degree: "B.Tech ECE", currentCompany: "HPCL", designation: "Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Kapu", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Telugu", familyType: "Joint", manglik: "No", languagesKnown: ["Telugu", "English", "Hindi"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f035", firstName: "Vandana", lastName: "Trivedi", gender: "Female", age: 28, dateOfBirth: "1996-04-19", city: "Indore", country: "India", height: 163, income: 1100000, degree: "M.Sc Biotechnology", currentCompany: "Lupin Pharma", designation: "Research Scientist", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f036", firstName: "Sakshi", lastName: "Chauhan", gender: "Female", age: 24, dateOfBirth: "2000-11-03", city: "Agra", country: "India", height: 156, income: 480000, degree: "B.A Political Science", currentCompany: "NGO Sector", designation: "Programme Officer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 3, horoscopeMatch: "Not Important" },
  { id: "f037", firstName: "Ramya", lastName: "Subramanian", gender: "Female", age: 26, dateOfBirth: "1998-07-27", city: "Madurai", country: "India", height: 155, income: 650000, degree: "B.E Civil", currentCompany: "L&T", designation: "Site Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tamil", familyType: "Joint", manglik: "No", languagesKnown: ["Tamil", "English"], siblings: 2, horoscopeMatch: "Must" },
  { id: "f038", firstName: "Aarti", lastName: "Saxena", gender: "Female", age: 27, dateOfBirth: "1997-01-16", city: "Kanpur", country: "India", height: 160, income: 700000, degree: "B.Sc Maths", currentCompany: "LIC India", designation: "Development Officer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Kayastha", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f039", firstName: "Nia", lastName: "Fernandes", gender: "Female", age: 27, dateOfBirth: "1997-09-04", city: "Goa", country: "India", height: 164, income: 850000, degree: "B.A English Literature", currentCompany: "BBC Media", designation: "Journalist", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Christian", caste: "Catholic", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Konkani", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Konkani", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f040", firstName: "Poonam", lastName: "Ahluwalia", gender: "Female", age: 26, dateOfBirth: "1998-05-17", city: "Amritsar", country: "India", height: 161, income: 780000, degree: "MBA Marketing", currentCompany: "HUL", designation: "Brand Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Sikh", caste: "Ahluwalia", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Punjabi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f041", firstName: "Kirti", lastName: "Chouhan", gender: "Female", age: 25, dateOfBirth: "1999-03-09", city: "Bhopal", country: "India", height: 158, income: 600000, degree: "BBA", currentCompany: "Bajaj Finserv", designation: "Relationship Executive", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "f042", firstName: "Swapna", lastName: "Bhatia", gender: "Female", age: 28, dateOfBirth: "1996-08-01", city: "Delhi", country: "India", height: 165, income: 1600000, degree: "PGDM IIM", currentCompany: "Boston Consulting Group", designation: "Consultant", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Khatri", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "f043", firstName: "Sonal", lastName: "Mehrotra", gender: "Female", age: 25, dateOfBirth: "1999-11-26", city: "Lucknow", country: "India", height: 159, income: 700000, degree: "B.Tech CS", currentCompany: "HCL", designation: "Software Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f044", firstName: "Sandhya", lastName: "Menon", gender: "Female", age: 27, dateOfBirth: "1997-04-08", city: "Kozhikode", country: "India", height: 157, income: 800000, degree: "B.A Economics", currentCompany: "Federal Bank", designation: "Credit Analyst", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "Yes", religion: "Hindu", caste: "Menon", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "No", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f045", firstName: "Natasha", lastName: "D'Souza", gender: "Female", age: 26, dateOfBirth: "1998-02-21", city: "Mumbai", country: "India", height: 163, income: 1000000, degree: "B.A Sociology", currentCompany: "Accenture", designation: "Strategy Consultant", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Christian", caste: "Roman Catholic", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Konkani", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["English", "Hindi", "Marathi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "f046", firstName: "Seema", lastName: "Soni", gender: "Female", age: 25, dateOfBirth: "1999-06-14", city: "Jaipur", country: "India", height: 156, income: 520000, degree: "B.Sc Home Science", currentCompany: "Self-employed", designation: "Caterer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Soni", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 3, horoscopeMatch: "Must" },
  { id: "f047", firstName: "Radhika", lastName: "Tiwari", gender: "Female", age: 27, dateOfBirth: "1997-12-30", city: "Raipur", country: "India", height: 160, income: 680000, degree: "M.A English", currentCompany: "Media House", designation: "Copy Editor", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Preferred" },
  { id: "f048", firstName: "Pinki", lastName: "Yadav", gender: "Female", age: 24, dateOfBirth: "2000-04-25", city: "Patna", country: "India", height: 155, income: 450000, degree: "B.Sc Nursing", currentCompany: "PMCH Hospital", designation: "Staff Nurse", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Yadav", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Bhojpuri", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English", "Bhojpuri"], siblings: 4, horoscopeMatch: "Not Important" },
  { id: "f049", firstName: "Garima", lastName: "Srivastava", gender: "Female", age: 26, dateOfBirth: "1998-09-08", city: "Gorakhpur", country: "India", height: 158, income: 580000, degree: "B.Ed", currentCompany: "DPS School", designation: "Teacher", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Kayastha", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "f050", firstName: "Vinitha", lastName: "George", gender: "Female", age: 27, dateOfBirth: "1997-11-22", city: "Thrissur", country: "India", height: 161, income: 900000, degree: "BDS Dentistry", currentCompany: "Private Clinic", designation: "Dentist", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Maybe", religion: "Christian", caste: "Orthodox", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 2, horoscopeMatch: "Not Important" },
];

const maleProfiles = [
  { id: "m001", firstName: "Arjun", lastName: "Desai", gender: "Male", age: 30, dateOfBirth: "1994-05-12", city: "Mumbai", country: "India", height: 178, income: 1500000, degree: "B.Tech CS", currentCompany: "TCS", designation: "Tech Lead", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Marathi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m002", firstName: "Kunal", lastName: "Nair", gender: "Male", age: 32, dateOfBirth: "1992-08-20", city: "Bangalore", country: "India", height: 180, income: 2000000, degree: "MBA Finance", currentCompany: "Goldman Sachs", designation: "Associate", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Nair", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "No", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "m003", firstName: "Shyam", lastName: "Patel", gender: "Male", age: 29, dateOfBirth: "1995-03-07", city: "Ahmedabad", country: "India", height: 173, income: 1200000, degree: "B.Com", currentCompany: "Family Business", designation: "Partner", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Patel", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Joint", manglik: "No", languagesKnown: ["Gujarati", "Hindi"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m004", firstName: "Tarun", lastName: "Khanna", gender: "Male", age: 31, dateOfBirth: "1993-11-15", city: "Delhi", country: "India", height: 177, income: 2500000, degree: "IIT Delhi B.Tech", currentCompany: "Microsoft", designation: "Senior Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Khatri", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m005", firstName: "Vivek", lastName: "Menon", gender: "Male", age: 28, dateOfBirth: "1996-07-23", city: "Chennai", country: "India", height: 174, income: 1100000, degree: "B.E EEE", currentCompany: "BHEL", designation: "Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Menon", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Malayalam", familyType: "Joint", manglik: "No", languagesKnown: ["Malayalam", "Tamil", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m006", firstName: "Varun", lastName: "Bhatia", gender: "Male", age: 33, dateOfBirth: "1991-02-01", city: "Chandigarh", country: "India", height: 182, income: 3000000, degree: "MBA IIM", currentCompany: "Amazon India", designation: "Sr Product Manager", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Khatri", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m007", firstName: "Suresh", lastName: "Krishnamurthy", gender: "Male", age: 30, dateOfBirth: "1994-10-10", city: "Coimbatore", country: "India", height: 171, income: 1300000, degree: "B.E Mech", currentCompany: "Rane Group", designation: "Project Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tamil", familyType: "Joint", manglik: "No", languagesKnown: ["Tamil", "English"], siblings: 2, horoscopeMatch: "Must" },
  { id: "m008", firstName: "Mohit", lastName: "Aggarwal", gender: "Male", age: 29, dateOfBirth: "1995-06-18", city: "Delhi", country: "India", height: 175, income: 1700000, degree: "CA CFA", currentCompany: "KPMG Advisory", designation: "Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Agarwal", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m009", firstName: "Faisal", lastName: "Qureshi", gender: "Male", age: 31, dateOfBirth: "1993-01-28", city: "Mumbai", country: "India", height: 179, income: 2200000, degree: "BArch", currentCompany: "Hafeez Contractor Firm", designation: "Senior Architect", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Muslim", caste: "Qureshi", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Urdu", familyType: "Joint", manglik: "N/A", languagesKnown: ["Urdu", "Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "m010", firstName: "Roshan", lastName: "George", gender: "Male", age: 29, dateOfBirth: "1995-04-04", city: "Kochi", country: "India", height: 176, income: 1400000, degree: "MBA", currentCompany: "HDFC Life", designation: "Area Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Christian", caste: "Syrian Christian", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m011", firstName: "Sameer", lastName: "Chaudhary", gender: "Male", age: 35, dateOfBirth: "1989-08-14", city: "Delhi", country: "India", height: 183, income: 4500000, degree: "IIM MBA", currentCompany: "Mckinsey", designation: "Principal", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "m012", firstName: "Rohit", lastName: "Jain", gender: "Male", age: 28, dateOfBirth: "1996-12-08", city: "Udaipur", country: "India", height: 172, income: 900000, degree: "B.Tech Mining", currentCompany: "Vedanta", designation: "Shift Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Jain", diet: "Jain", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English", "Rajasthani"], siblings: 3, horoscopeMatch: "Preferred" },
  { id: "m013", firstName: "Kiran", lastName: "Kumar", gender: "Male", age: 30, dateOfBirth: "1994-09-19", city: "Mysore", country: "India", height: 170, income: 1100000, degree: "B.Tech CS", currentCompany: "Infosys", designation: "Senior Analyst", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Vokkaliga", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Kannada", familyType: "Nuclear", manglik: "No", languagesKnown: ["Kannada", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m014", firstName: "Harsh", lastName: "Vardhan", gender: "Male", age: 27, dateOfBirth: "1997-05-02", city: "Nagpur", country: "India", height: 174, income: 850000, degree: "B.Tech Civil", currentCompany: "NCC Limited", designation: "Site Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Marathi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m015", firstName: "Saurav", lastName: "Banerjee", gender: "Male", age: 31, dateOfBirth: "1993-07-27", city: "Kolkata", country: "India", height: 176, income: 1800000, degree: "IIT KGP M.Tech", currentCompany: "TATA Steel", designation: "Research Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Bengali", familyType: "Nuclear", manglik: "No", languagesKnown: ["Bengali", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m016", firstName: "Prateek", lastName: "Mishra", gender: "Male", age: 29, dateOfBirth: "1995-10-15", city: "Allahabad", country: "India", height: 175, income: 1000000, degree: "B.Tech CS IIT", currentCompany: "Byju's", designation: "Sr Developer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English", "Sanskrit"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m017", firstName: "Gaurav", lastName: "Srivastava", gender: "Male", age: 32, dateOfBirth: "1992-03-11", city: "Kanpur", country: "India", height: 179, income: 2800000, degree: "MBA", currentCompany: "Bain & Company", designation: "Consultant", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Kayastha", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "m018", firstName: "Aakash", lastName: "Tiwari", gender: "Male", age: 28, dateOfBirth: "1996-01-30", city: "Varanasi", country: "India", height: 171, income: 750000, degree: "B.Tech IT", currentCompany: "Wipro", designation: "Software Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m019", firstName: "Danish", lastName: "Siddiqui", gender: "Male", age: 30, dateOfBirth: "1994-06-09", city: "Lucknow", country: "India", height: 177, income: 1400000, degree: "M.Tech ECE", currentCompany: "ISRO", designation: "Scientist-C", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Muslim", caste: "Siddiqui", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Urdu", familyType: "Joint", manglik: "N/A", languagesKnown: ["Urdu", "Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "m020", firstName: "Sudhir", lastName: "Narayanan", gender: "Male", age: 35, dateOfBirth: "1989-04-17", city: "Bangalore", country: "India", height: 172, income: 5000000, degree: "PhD Computer Science", currentCompany: "IISc", designation: "Assistant Professor", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "No", openToPets: "Yes", religion: "Hindu", caste: "Iyengar", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tamil", familyType: "Nuclear", manglik: "No", languagesKnown: ["Tamil", "Kannada", "English"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "m021", firstName: "Yash", lastName: "Puri", gender: "Male", age: 27, dateOfBirth: "1997-02-26", city: "Jaipur", country: "India", height: 176, income: 950000, degree: "MBA Luxury Brand Mgmt", currentCompany: "Louis Vuitton India", designation: "Store Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "French"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m022", firstName: "Abhinav", lastName: "Sharma", gender: "Male", age: 30, dateOfBirth: "1994-11-03", city: "Pune", country: "India", height: 180, income: 1900000, degree: "B.Tech CS BITS Pilani", currentCompany: "Persistent Systems", designation: "Architect", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Maybe", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Marathi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m023", firstName: "Pranav", lastName: "Garg", gender: "Male", age: 28, dateOfBirth: "1996-08-15", city: "Delhi", country: "India", height: 175, income: 1300000, degree: "B.Tech EEE NIT", currentCompany: "Power Grid Corp", designation: "Assistant Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Agarwal", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m024", firstName: "Aditya", lastName: "Singh", gender: "Male", age: 32, dateOfBirth: "1992-05-21", city: "Noida", country: "India", height: 182, income: 3200000, degree: "MBA IIM Calcutta", currentCompany: "Marico", designation: "Category Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m025", firstName: "Rajkumar", lastName: "Pillai", gender: "Male", age: 29, dateOfBirth: "1995-09-07", city: "Trivandrum", country: "India", height: 173, income: 1250000, degree: "B.Tech CS NIT Calicut", currentCompany: "UST Global", designation: "Senior Developer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Nair", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "No", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m026", firstName: "Siddharth", lastName: "Malviya", gender: "Male", age: 27, dateOfBirth: "1997-12-13", city: "Indore", country: "India", height: 174, income: 800000, degree: "B.Pharm M.Pharm", currentCompany: "Cipla", designation: "Medical Representative", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m027", firstName: "Joel", lastName: "Mathew", gender: "Male", age: 30, dateOfBirth: "1994-03-25", city: "Ernakulam", country: "India", height: 178, income: 1600000, degree: "BDS MDS Orthodontics", currentCompany: "Own Clinic", designation: "Orthodontist", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "Yes", religion: "Christian", caste: "Catholic", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Malayalam", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m028", firstName: "Arun", lastName: "Krishnan", gender: "Male", age: 33, dateOfBirth: "1991-07-04", city: "Chennai", country: "India", height: 171, income: 2600000, degree: "MBBS MD Radiology", currentCompany: "Fortis Hospital", designation: "Radiologist", maritalStatus: "Divorced", wantKids: "Maybe", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Tamil", familyType: "Nuclear", manglik: "No", languagesKnown: ["Tamil", "English", "Hindi"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "m029", firstName: "Chirag", lastName: "Pandya", gender: "Male", age: 31, dateOfBirth: "1993-10-28", city: "Surat", country: "India", height: 170, income: 2000000, degree: "B.Tech Textile", currentCompany: "Welspun Group", designation: "GM Operations", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Patel", diet: "Jain", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Joint", manglik: "No", languagesKnown: ["Gujarati", "Hindi", "English"], siblings: 3, horoscopeMatch: "Must" },
  { id: "m030", firstName: "Manish", lastName: "Agnihotri", gender: "Male", age: 34, dateOfBirth: "1990-02-16", city: "Bhopal", country: "India", height: 177, income: 1700000, degree: "B.E CS", currentCompany: "MPSEDC", designation: "Deputy Director IT", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English", "Sanskrit"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m031", firstName: "Sanjeev", lastName: "Tiku", gender: "Male", age: 36, dateOfBirth: "1988-05-31", city: "Jammu", country: "India", height: 176, income: 3800000, degree: "MBA", currentCompany: "J&K Bank", designation: "AGM", maritalStatus: "Divorced", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Dogri", familyType: "Joint", manglik: "No", languagesKnown: ["Dogri", "Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "m032", firstName: "Nakul", lastName: "Oberoi", gender: "Male", age: 29, dateOfBirth: "1995-01-09", city: "Delhi", country: "India", height: 181, income: 2100000, degree: "B.Tech IIT Delhi", currentCompany: "Uber India", designation: "Senior Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Khatri", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "m033", firstName: "Karan", lastName: "Bedi", gender: "Male", age: 28, dateOfBirth: "1996-06-22", city: "Ludhiana", country: "India", height: 183, income: 1600000, degree: "B.E CS", currentCompany: "Siemens India", designation: "Automation Engineer", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Sikh", caste: "Bedi", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Punjabi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m034", firstName: "Prashant", lastName: "Wani", gender: "Male", age: 31, dateOfBirth: "1993-04-05", city: "Nagpur", country: "India", height: 173, income: 1400000, degree: "B.Arch", currentCompany: "Patel Engineering", designation: "Project Architect", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Mali", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Marathi", familyType: "Joint", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "m035", firstName: "Anirudh", lastName: "Raj", gender: "Male", age: 26, dateOfBirth: "1998-09-14", city: "Patna", country: "India", height: 170, income: 700000, degree: "B.Sc Physics Honors IIT", currentCompany: "Teaching Coaching", designation: "Faculty", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 3, horoscopeMatch: "Preferred" },
  { id: "m036", firstName: "Vikramjit", lastName: "Singh", gender: "Male", age: 34, dateOfBirth: "1990-12-19", city: "Chandigarh", country: "India", height: 185, income: 4200000, degree: "MBA Abroad", currentCompany: "Marriott Hotels", designation: "General Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Sikh", caste: "Jat", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Punjabi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m037", firstName: "Ansh", lastName: "Kapoor", gender: "Male", age: 27, dateOfBirth: "1997-08-06", city: "Mumbai", country: "India", height: 175, income: 1100000, degree: "BFA Film Direction", currentCompany: "Dharma Productions", designation: "Assistant Director", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "No", openToPets: "Yes", religion: "Hindu", caste: "Khatri", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Punjabi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English", "Punjabi"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "m038", firstName: "Debashish", lastName: "Roy", gender: "Male", age: 30, dateOfBirth: "1994-07-01", city: "Kolkata", country: "India", height: 174, income: 1500000, degree: "CA", currentCompany: "Deloitte", designation: "Senior Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Bengali", familyType: "Nuclear", manglik: "No", languagesKnown: ["Bengali", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m039", firstName: "Manan", lastName: "Trivedi", gender: "Male", age: 28, dateOfBirth: "1996-02-28", city: "Vadodara", country: "India", height: 172, income: 900000, degree: "B.Tech CS", currentCompany: "Reliance Jio", designation: "Network Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Joint", manglik: "No", languagesKnown: ["Gujarati", "Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m040", firstName: "Rajeev", lastName: "Gowda", gender: "Male", age: 33, dateOfBirth: "1991-11-24", city: "Mysore", country: "India", height: 170, income: 2200000, degree: "LLB LLM Harvard", currentCompany: "Cyril Amarchand Mangaldas", designation: "Senior Associate", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Vokkaliga", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Kannada", familyType: "Nuclear", manglik: "No", languagesKnown: ["Kannada", "English", "Hindi"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m041", firstName: "Parthiv", lastName: "Goswami", gender: "Male", age: 29, dateOfBirth: "1995-04-12", city: "Guwahati", country: "India", height: 171, income: 1100000, degree: "MBBS MD Pediatrics", currentCompany: "GMCH Guwahati", designation: "Junior Resident", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Assamese", familyType: "Nuclear", manglik: "No", languagesKnown: ["Assamese", "Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
  { id: "m042", firstName: "Amol", lastName: "Naik", gender: "Male", age: 27, dateOfBirth: "1997-07-18", city: "Nashik", country: "India", height: 173, income: 850000, degree: "B.Tech ECE", currentCompany: "Mahindra Electric", designation: "Embedded Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Hindu", caste: "CKP", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Marathi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m043", firstName: "Nitin", lastName: "Taneja", gender: "Male", age: 32, dateOfBirth: "1992-01-06", city: "Gurgaon", country: "India", height: 180, income: 3500000, degree: "IIT Delhi MTech", currentCompany: "Qualcomm India", designation: "Principal Engineer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Hindi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 0, horoscopeMatch: "Not Important" },
  { id: "m044", firstName: "Kabir", lastName: "Rathore", gender: "Male", age: 28, dateOfBirth: "1996-10-21", city: "Jodhpur", country: "India", height: 178, income: 1200000, degree: "LLB", currentCompany: "Rajasthan High Court", designation: "Advocate", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Rajput", diet: "Non-Vegetarian", smoking: "No", drinking: "Occasionally", motherTongue: "Rajasthani", familyType: "Joint", manglik: "No", languagesKnown: ["Rajasthani", "Hindi", "English"], siblings: 3, horoscopeMatch: "Preferred" },
  { id: "m045", firstName: "Omkar", lastName: "Joshi", gender: "Male", age: 30, dateOfBirth: "1994-08-29", city: "Pune", country: "India", height: 172, income: 1600000, degree: "M.Tech AI COEP", currentCompany: "NVIDIA India", designation: "AI Researcher", maritalStatus: "Never Married", wantKids: "Maybe", openToRelocate: "Yes", openToPets: "Yes", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Marathi", familyType: "Nuclear", manglik: "No", languagesKnown: ["Marathi", "Hindi", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m046", firstName: "Abrar", lastName: "Hussain", gender: "Male", age: 29, dateOfBirth: "1995-03-02", city: "Bhopal", country: "India", height: 175, income: 1100000, degree: "MBBS", currentCompany: "Hamidia Hospital", designation: "Medical Officer", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Muslim", caste: "Hussain", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Urdu", familyType: "Joint", manglik: "N/A", languagesKnown: ["Urdu", "Hindi", "English"], siblings: 3, horoscopeMatch: "Not Important" },
  { id: "m047", firstName: "Surya", lastName: "Venugopal", gender: "Male", age: 28, dateOfBirth: "1996-05-16", city: "Trivandrum", country: "India", height: 174, income: 1350000, degree: "B.Tech CS NIT Trichy", currentCompany: "ISRO", designation: "Scientist-B", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Nair", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Malayalam", familyType: "Nuclear", manglik: "No", languagesKnown: ["Malayalam", "Tamil", "English"], siblings: 1, horoscopeMatch: "Not Important" },
  { id: "m048", firstName: "Mihir", lastName: "Shah", gender: "Male", age: 31, dateOfBirth: "1993-09-10", city: "Surat", country: "India", height: 169, income: 2800000, degree: "B.Tech Diamonds", currentCompany: "Shrenuj Diamonds", designation: "Director", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "No", openToPets: "No", religion: "Hindu", caste: "Baniya", diet: "Jain", smoking: "No", drinking: "No", motherTongue: "Gujarati", familyType: "Joint", manglik: "No", languagesKnown: ["Gujarati", "Hindi", "English"], siblings: 2, horoscopeMatch: "Must" },
  { id: "m049", firstName: "Rahil", lastName: "Shaikh", gender: "Male", age: 29, dateOfBirth: "1995-12-04", city: "Mumbai", country: "India", height: 177, income: 1600000, degree: "MBA NMIMS", currentCompany: "JSW Steel", designation: "Marketing Manager", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Yes", openToPets: "No", religion: "Muslim", caste: "Sheikh", diet: "Non-Vegetarian", smoking: "No", drinking: "No", motherTongue: "Urdu", familyType: "Nuclear", manglik: "N/A", languagesKnown: ["Urdu", "Hindi", "English", "Marathi"], siblings: 2, horoscopeMatch: "Not Important" },
  { id: "m050", firstName: "Ayush", lastName: "Pandey", gender: "Male", age: 26, dateOfBirth: "1998-06-20", city: "Lucknow", country: "India", height: 172, income: 650000, degree: "B.Sc Mathematics", currentCompany: "Career Launcher", designation: "Faculty", maritalStatus: "Never Married", wantKids: "Yes", openToRelocate: "Maybe", openToPets: "No", religion: "Hindu", caste: "Brahmin", diet: "Vegetarian", smoking: "No", drinking: "No", motherTongue: "Hindi", familyType: "Joint", manglik: "No", languagesKnown: ["Hindi", "English"], siblings: 2, horoscopeMatch: "Preferred" },
];

// Get all female profiles (for matching with male customers)
export const getFemaleProfiles = () => femaleProfiles;

// Get all male profiles (for matching with female customers)
export const getMaleProfiles = () => maleProfiles;

// Get all profiles
export const getAllMatchProfiles = () => [...femaleProfiles, ...maleProfiles];
